// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARJieVCcKunzzrHKOR3EhF21IK8wTKmz4',
    appId: '1:679728678272:web:ce69df03c375ecd3dbed65',
    messagingSenderId: '679728678272',
    projectId: 'jurnal-classification',
    authDomain: 'jurnal-classification.firebaseapp.com',
    storageBucket: 'jurnal-classification.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpzS3_vAv6oueGh6CDf6d1uY_zzgjOjN4',
    appId: '1:679728678272:ios:a70d49b34e488d72dbed65',
    messagingSenderId: '679728678272',
    projectId: 'jurnal-classification',
    storageBucket: 'jurnal-classification.appspot.com',
    iosClientId: '679728678272-d3379pnl649o1mdfdrqaef0n9ashpelp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pencarianJurnal',
  );
}
